janash/periodic-table

elements/rubidium.md

This pull request adds a page to the periodic table for the element rubidium.

add Rb element page

---

elements/Osmium.md

Added the Osmium file with some "dense" facts.

Made the Osmium.md file

---

elements/iridium.md

This pull request adds a page to the periodic table for the element iridium.

Add Iridium page

---

californium.md
elements/californium.md

This pull request adds a page to the periodic table for the element Californium.

Californium

---

elements/nickel.md

This pull request adds a page to the periodic table for the element nickel.

Add Nickel page

---

elements/carbon.md

This pull request  adds a page to the periodic table for the element carbon

Add carbon

---

elements/oxygen.md

This pull request adds a page for oxygen

Add oxygen page

---

elements/tennessine.md

This pull request adds a page to the periodic table for the element tennessine.

Add tennessine page

---

elements/arsenic.md

Adding a new element, arsenic, to the periodic table.

arsenic fun fact

---

elements/tungsten.md

This pull request adds a page to the periodic table for the element tungsten

Add tungsten page

---

README.md
elements/sodium.md

This pull request adds a page to the periodic table for the element sodium.

Add sodium page

---

elements/berkelium.md

Add Berkelium to the period table!

added berkelium

---

README.md
elements/sulfur.md

This is an addition of sulfur to the periodic table website
-[x] create page

Add Sulfur page

---

elements/helium.md

add helium

---

elements/astatine.md

This pull request adds a page to the periodic table for the element Astatine.
-[x] create page

Add Astatine page

---

elements/zinc.md

This pull request adds a page to the periodic table for the element zinc.

added zinc.md

---

elements/oxygen.md

This pull request adds a page to the periodic table for oxygen

Add Oxygen2

---

elements/boron.md

This pull request adds a page to the periodic table for element boron.

added boron

---

elements/iridium.md

This pull request adds a page to the periodic table for the element iridium

added element Ir

---

elements/barium.md

This pull request adds a page on barium that is copied from Wikipedia

Add barium page

---

elements/vanadium.md

This pull request adds a page to the periodic table for the element Vanadium

added file vanadium.md

---

elements/zinc.md

This pull request adds description for the element zinc in the periodic table.

Add Zinc page
